<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit440e289796dc965fc1a97a18dc0f77b2
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit440e289796dc965fc1a97a18dc0f77b2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit440e289796dc965fc1a97a18dc0f77b2::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
