<div class="container-fluid">
	<div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Ticket Information</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="<?php echo base_url();?>">Dashboard</a></li>
                <li class="active">Ticket Information Page</li>
            </ol>
        </div>
    </div>
    
    <?php 
		if($ticket_info[0]->special_ticket == 1){$ticket_type = 'PM';}elseif($ticket_info[0]->special_ticket == 2){$ticket_type = 'GWC';}elseif($ticket_info[0]->special_ticket == 3){$ticket_type = 'GV';}elseif($ticket_info[0]->special_ticket == 5){$ticket_type = 'Quick';}else{$ticket_type = 'GSS';}
		$dept_name = admin_helper::get_role_name($ticket_info[0]->assign_to_dept);
		$replies = ''; 
		$reply_notes = admin_helper::get_ticket_notes_replies($ticket_info[0]->id);
		
		$head = '<div class="chat-box"><ul class="chat-list slimscrolll p-0">';
		$foot = '</ul></div>';
		if(!empty($reply_notes) && isset($reply_notes)){
			foreach($reply_notes as $reply){
				$repDate = date("m-d-Y", strtotime($reply->added_date));
				$repTime = date("h:i a", strtotime($reply->added_date));
					$replies .= '<li class="m-b-10"><div class="chat-body"><div class="chat-text"><h4>'.$reply->added_by.'</h4><p>'.htmlspecialchars_decode($reply->message).'</p><b>'.$repDate.' '.$repTime.'</b></div></div></li>';
			}
			$replies = $head.$replies.$foot;
		}

		if($ticket_info[0]->ticketStatus == 1){$ticket_status = 'PENDING';}elseif($ticket_info[0]->ticketStatus == 2){$ticket_status = 'PICKUPED';}else{$ticket_status = 'CLOSED';}
	?>    
    <div class="row">
        <div class="col-md-12">
            <div class="white-box printableArea">
                <h3><b>Ticket #<?php echo $ticket_type.$ticket_info[0]->id;?> Generated by "<?php echo $ticket_info[0]->ticketGenBy;?>" Assigned Department "<?php echo $dept_name[0]->name;?>"</b> <span class="pull-right">
				<?php echo date("M d, Y h:i", strtotime($ticket_info[0]->ticketDate));?></span></h3>
                <hr>
                <div class="row">
                	<div class="col-md-6"></div>
                    <div class="col-md-6 pull-right">
						<?php if($ticket_info[0]->special_ticket == 1){?>
                            <button type="button" class="btn btn-danger waves-effect waves-light"><?php echo $ticket_status?></button>
                        <?php }else{if($ticket_info[0]->serviceRec == 'yes'){?>
                            <button type="button" class="btn btn-danger waves-effect waves-light"><blink style="color:#FFF;"><?php echo $ticket_status?></blink></button>
                        <?php }else{?>
                            <button type="button" class="btn btn-danger waves-effect waves-light"><?php echo $ticket_status?></button>
                        <?php }}?>
                    </div>
                </div>
                <hr>
                <?php if($ticket_info[0]->special_ticket == 0 or $ticket_info[0]->special_ticket == 2){?>
															<?php if($ticket_info[0]->houseGuest == 'yes'){?>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Room Number:</b> <?php echo $ticket_info[0]->guestRoomNumber;?></div>
                                                                    <div class="col-md-6"><b>Room Type:</b> <?php echo $ticket_info[0]->guestRoomType;?></div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-md-4"><b>Guest Name:</b> <?php echo $ticket_info[0]->guestName;?></div>
                                                                    <div class="col-md-4"><b>Email:</b> <?php echo $ticket_info[0]->guestEmail;?></div>
                                                                    <div class="col-md-4"><b>Phone:</b> <?php echo $ticket_info[0]->guestNumber;?></div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>ARRIVAL DATE:</b> <?php echo date("m/d/Y", strtotime($ticket_info[0]->arrivalDate));?></div>
                                                                    <div class="col-md-6"><b>DEPARTURE DATE:</b> <?php echo date("m/d/Y", strtotime($ticket_info[0]->departDate));?></div>
                                                                </div>
                                                            <?php }elseif($ticket_info[0]->houseGuest == 'no'){
                                                                if($ticket_info[0]->furtherReservation == 'yes'){?>
                                                                    <div class="row">
                                                                        <div class="col-md-6"><b>Room Type:</b> <?php echo $ticket_info[0]->guestRoomType;?></div>
                                                                        <div class="col-md-6"></div>
                                                                    </div>
                                                                <?php }?>
                                                                <div class="row">
                                                                    <div class="col-md-4"><b>Guest Name:</b> <?php echo $ticket_info[0]->guestName;?></div>
                                                                    <div class="col-md-4"><b>Email:</b> <?php echo $ticket_info[0]->guestEmail;?></div>
                                                                    <div class="col-md-4"><b>Phone:</b> <?php echo $ticket_info[0]->guestNumber;?></div>
                                                                </div>
                                                                <?php if($ticket_info[0]->furtherReservation == 'yes'){?>
                                                                    <div class="row">
                                                                        <div class="col-md-6"><b>ARRIVAL DATE:</b><?php echo date("m/d/Y", strtotime($ticket_info[0]->arrivalDate));?></div>
                                                                        <div class="col-md-6"><b>DEPARTURE DATE:</b> <?php echo date("m/d/Y", strtotime($ticket_info[0]->departDate));?></div>
                                                                    </div>
                                                                <?php }?>
                                                            <?php }else{?>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Standard Guest:</b></div>
                                                                    <div class="col-md-6"></div>
                                                                </div>
                                                            <?php }?>
                                                            <?php if($ticket_info[0]->assign_to_dept == 3){?>
                                                            	<h3><b class="text-danger">FRONT DESK</b></h3>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Notes:</b> <?php echo $ticket_info[0]->frontDeskNotes;?></div>
                                                                    <div class="col-md-6"></div>
                                                                </div>
                                                            <?php }?>
                                                            <?php if($ticket_info[0]->assign_to_dept == 4){?>
                                                            	<h3><b class="text-danger">HOUSEKEEPING</b></h3>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Notes:</b> <?php echo $ticket_info[0]->houseKeepingNotes;?></div>
                                                                    <div class="col-md-6"><b>Service:</b> <?php echo $ticket_info[0]->houseKeepingSer;?></div>
                                                                </div>
                                                            <?php }?>
                                                            <?php if($ticket_info[0]->assign_to_dept == 5){?>
                                                            	<h3><b class="text-danger">FOOD & BEVERAGE</b></h3>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Service:</b> <?php echo ucwords($ticket_info[0]->foodsService);?></div>
                                                                    <div class="col-md-6"><b>Name of group:</b> <?php echo ucwords($ticket_info[0]->nameOfGroup);?></div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Notes:</b> <?php echo $ticket_info[0]->foodGuestNotes;?></div>
                                                                    <div class="col-md-6"></div>
                                                                </div>
                                                            <?php }?>
                                                            <?php if($ticket_info[0]->assign_to_dept == 6){?>
                                                            	<h3><b class="text-danger">SALES</b></h3>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Company:</b> <?php echo $ticket_info[0]->saleCompany;?></div>
                                                                    <div class="col-md-6"><b>Email:</b> <?php echo $ticket_info[0]->salesMail;?></div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Primery Phone:</b> <?php echo $ticket_info[0]->salesPhone;?></div>
                                                                    <div class="col-md-6"><b>Secondary Phone:</b> <?php echo $ticket_info[0]->salesPhone2;?></div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Call Time:</b> <?php echo $ticket_info[0]->salesCallTime;?></div>
                                                                    <div class="col-md-6"><b>Bring to hotel from:</b> <?php echo $ticket_info[0]->bringsHotel;?></div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Urgent Request:</b> <?php echo $ticket_info[0]->urgentRequest;?></div>
                                                                    <div class="col-md-6"></div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Budget $$:</b> <?php echo $ticket_info[0]->guestBudget;?></div>
                                                                    <div class="col-md-6"></div>
                                                                </div>
                                                                <?php if($ticket_info[0]->guestRoomNeed == 'yes'){?>
                                                                	<h3><b>GUEST ROOMS NEEDED</b></h3>
                                                                    <div class="row">
                                                                        <div class="col-md-4"><b>ARRIVAL DATE:</b><?php echo date("m/d/Y", strtotime($ticket_info[0]->guestarivalDate));?></div>
                                                                        <div class="col-md-4"><b>DEPARTURE DATE:</b> <?php echo date("m/d/Y", strtotime($ticket_info[0]->guestDepartDate));?></div>
                                                                        <div class="col-md-4"><b>No. of Guest Rooms:</b> <?php echo $ticket_info[0]->guestRooms;?></div>
                                                                    </div>
                                                                <?php }else{?>
                                                                    <div class="row">
                                                                        <div class="col-md-6"><b>ARRIVAL DATE:</b><?php echo date("m/d/Y", strtotime($ticket_info[0]->guestarivalDate));?></div>
                                                                        <div class="col-md-6"></div>
                                                                    </div>
                                                                <?php }?>
                                                                <?php if($ticket_info[0]->meetingRoomNeeded == 'yes'){?>
                                                                	<h3><b>MEETING ROOMS NEEDED</b></h3>
                                                                    <div class="row">
                                                                        <div class="col-md-6"><b>No. of People for meetings:</b> <?php echo $ticket_info[0]->peoples;?></div>
                                                                        <div class="col-md-6"></div>
                                                                    </div>
                                                                <?php }?>
                                                                <?php if($ticket_info[0]->foodNeed == 'yes'){?>
                                                                	<h3><b>FOOD NEEDED</b></h3>
                                                                    <div class="row">
                                                                        <div class="col-md-6"><b>Food Needed:</b> <?php echo $ticket_info[0]->foodNeed;?></div>
                                                                        <div class="col-md-6"></div>
                                                                    </div>
                                                                <?php }?>
                                                                <?php if($ticket_info[0]->returnGuest == 'yes'){?>
                                                                	<h3><b>RETURNED GUEST</b></h3>
                                                                    <div class="row">
                                                                        <div class="col-md-6"><b>Returned Guest:</b> <?php echo $ticket_info[0]->returnGuest;?></div>
                                                                        <div class="col-md-6"></div>
                                                                    </div>
                                                                <?php }?>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Notes:</b> <?php echo $ticket_info[0]->saleNotes;?></div>
                                                                    <div class="col-md-6"></div>
                                                                </div>
                                                            <?php }?>
                                                            <?php if($ticket_info[0]->assign_to_dept == 7){?>
                                                            	<h3><b class="text-danger">MAINTENANCE</b></h3>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Service:</b> <?php echo ucwords($ticket_info[0]->maintServ);?></div>
                                                                    <div class="col-md-6"><b>Needs:</b> <?php echo ucwords($ticket_info[0]->maintExplain);?></div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Notes:</b> <?php echo $ticket_info[0]->mainnotes;?></div>
                                                                    <div class="col-md-6"></div>
                                                                </div>
                                                            <?php }?>
                                                            <?php if($ticket_info[0]->assign_to_dept == 2){?>
                                                            	<h3><b class="text-danger">MANAGER ON DUTY</b></h3>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Service:</b> <?php echo ucwords($ticket_info[0]->mangrDutyConcern);?></div>
                                                                    <div class="col-md-6"><b>Needs:</b> <?php echo ucwords($ticket_info[0]->mangrExpalin);?></div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Notes:</b> <?php echo $ticket_info[0]->mingrNotes;?></div>
                                                                    <div class="col-md-6"></div>
                                                                </div>
                                                            <?php }?>
                                                            <div class="row">
                                                                <div class="col-md-6" id="replies_<?php echo $ticket_info[0]->id;?>"><?php echo $replies;?></div>
                                                                <div class="col-md-6">
                                                                    <?php if($ticket_info[0]->filename !=''){?>
                                                                        <h3><b class="text-danger">ATTACHMENT</b></h3>
                                                                        <img src="<?php echo base_url();?>assets/images/ticket_images/<?php echo $ticket_info[0]->filename;?>" width="300" height="300"/>
                                                                    <?php }?>
                                                                </div>
                                                            </div>
                                                            <?php }
					elseif($ticket_info[0]->special_ticket == 5){?>
                        <div class="row">
                            <div class="col-md-6"><b>Room Number:</b> <?php echo $ticket_info[0]->guestRoomNumber;?></div>
                            <div class="col-md-6"><b>Room Type:</b> <?php echo $ticket_info[0]->guestRoomType;?></div>
                        </div>
                        <?php if($ticket_info[0]->assign_to_dept == 3){?>
                            <h3><b class="text-danger">FRONT DESK</b></h3>
                            <div class="row">
                                <div class="col-md-6"><b>Notes:</b> <?php echo $ticket_info[0]->frontDeskNotes;?></div>
                                <div class="col-md-6"></div>
                            </div>
                        <?php }?>
                        <?php if($ticket_info[0]->assign_to_dept == 4){?>
                            <h3><b class="text-danger">HOUSEKEEPING</b></h3>
                            <div class="row">
                                <div class="col-md-6"><b>Notes:</b> <?php echo $ticket_info[0]->houseKeepingNotes;?></div>
                                <div class="col-md-6"></div>
                            </div>
                        <?php }?>
                        <?php if($ticket_info[0]->assign_to_dept == 5){?>
                            <h3><b class="text-danger">FOOD & BEVERAGE</b></h3>
                            <div class="row">
                                <div class="col-md-6"><b>Notes:</b> <?php echo $ticket_info[0]->foodGuestNotes;?></div>
                                <div class="col-md-6"></div>
                            </div>
                        <?php }?>
                        <?php if($ticket_info[0]->assign_to_dept == 6){?>
                            <h3><b class="text-danger">SALES</b></h3>
                            <div class="row">
                                <div class="col-md-6"><b>Notes:</b> <?php echo $ticket_info[0]->saleNotes;?></div>
                                <div class="col-md-6"></div>
                            </div>
                        <?php }?>
                        <?php if($ticket_info[0]->assign_to_dept == 7){?>
                            <h3><b class="text-danger">MAINTENANCE</b></h3>
                            <div class="row">
                                <div class="col-md-6"><b>Notes:</b> <?php echo $ticket_info[0]->mainnotes;?></div>
                                <div class="col-md-6"></div>
                            </div>
                        <?php }?>
                        <?php if($ticket_info[0]->assign_to_dept == 2){?>
                            <div class="row">
                                <div class="col-md-6"><b>Notes:</b> <?php echo $ticket_info[0]->mingrNotes;?></div>
                                <div class="col-md-6"></div>
                            </div>
                        <?php }?>
                        <div class="row">
                                <div class="col-md-6"><b>Service:</b> <?php echo ucwords($ticket_info[0]->maintServ);?></div>
                                <div class="col-md-6"></div>
                            </div>
                        <div class="row">
                            <div class="col-md-6" id="replies_<?php echo $ticket_info[0]->id;?>"><?php echo $replies;?></div>
                            <div class="col-md-6"></div>
                        </div>
                    <?php }
					else{?>
																<!--<div class="row">
                                                                    <div class="col-md-6"><b>Room#:</b> <?php echo $ticket_info[0]->ticketGenBy;?></div>
                                                                    <div class="col-md-6"><b>Room Type:</b> <?php echo $ticket_info[0]->ticketGenBy;?></div>
                                                                </div>-->
																<div class="row">
                                                                    <div class="col-md-4"><b>Category:</b> <?php $cat_name = admin_helper::get_category_name($ticket_info[0]->cat_id); echo $cat_name[0]->cat_name;?></div>
                                                                    <div class="col-md-4"><b>Item Name:</b> <?php $subcat_name = admin_helper::get_subcategory_name($ticket_info[0]->item_id); echo $subcat_name[0]->subcat_name;?></div>
                                                                    <div class="col-md-4"><b>Quarter:</b> <?php echo $ticket_info[0]->quarter;?></div>
                                                                </div>
															<hr />
															<?php if($ticket_info[0]->pm_status == 'complete'){?>
                                                                <h3><b class="text-danger"><?php echo ucwords($ticket_info[0]->pm_status);?></b></h3>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Were repairs necessary?:</b> <?php echo $ticket_info[0]->repair_req;?></div>
                                                                    <div class="col-md-6"><b>Condition rate of item:</b> <?php echo $ticket_info[0]->ratting;?></div>
                                                                </div>
                                                                <?php if($ticket_info[0]->repair_req == 'yes'){?>
                                                                    <div class="row">
                                                                        <div class="col-md-6"><b>What was speficially repaired?:</b> <?php echo $ticket_info[0]->spsfic_req;?></div>
                                                                        <div class="col-md-6"></div>
                                                                    </div>
                                                                <?php }?>
                                                                    <div class="row">
                                                                        <div class="col-md-6"><b>Notes:</b> <?php echo htmlspecialchars_decode($ticket_info[0]->pm_notes);?></div>
                                                                        <div class="col-md-6">
                                                                            <?php if($ticket_info[0]->pm_filename !=''){?>
                                                                                <img src="<?php echo base_url();?>assets/images/pmp_images/<?php echo $ticket_info[0]->pm_filename;?>" width="300" height="300"/>
                                                                            <?php }?>
                                                                        </div>
                                                                    </div>
                                                                <?php }else{?>
                                                                <h3><b class="text-danger"><?php echo ucwords($ticket_info[0]->pm_status);?></b></h3>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Flagged Type:</b> <?php echo $ticket_info[0]->flage_type;?></div>
                                                                    <div class="col-md-6"><b>Flagged Type:</b> <?php echo $ticket_info[0]->flage_type_2;?></div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Outside Vendor Required?:</b> <?php echo $ticket_info[0]->vendor_req;?></div>
                                                                    <div class="col-md-6"></div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-md-6"><b>Notes:</b> <?php echo htmlspecialchars_decode($ticket_info[0]->pm_notes);?></div>
                                                                    <div class="col-md-6"><?php if($ticket_info[0]->pm_filename !=''){?><img src="<?php echo base_url();?>assets/images/pmp_images/<?php echo $ticket_info[0]->pm_filename;?>" width="300" height="300"/><?php }?></div>
                                                                </div>
                                                                <?php }?>
                                                            <div class="row">
                                                                <div class="col-md-6" id="replies_<?php echo $ticket_info[0]->id;?>"><?php echo $replies;?></div>
                                                                <div class="col-md-6"></div>
                                                            </div>
                                                            <?php }?>
                <?php /*?><div class="row">
                <?php if($ticket_info[0]->houseGuest == 'yes'){?>
                    <div class="col-md-12">
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger"><?php $rolename = admin_helper::get_role_name($ticket_info[0]->assign_to_dept); echo $rolename[0]->name; if($ticket_info[0]->serviceRec == 'yes'){echo ' / SERVICE RECOVERY';}?></b></h3>
                                <h4 class="font-bold"><?php if($ticket_info[0]->houseGuest == 'yes'){echo 'In-House';}elseif($ticket_info[0]->houseGuest == 'no'){echo 'Future';}else{echo 'Standard';}?> Guest</h4>
                                <p class="text-muted m-l-10"><b>Guest Name:</b> <?php echo $ticket_info[0]->guestName;?></p>
                                <p class="text-muted m-l-10"><b>Guest Phone:</b> <?php echo $ticket_info[0]->guestNumber;?></p>
                                <p class="text-muted m-l-10"><b>Arrival Date:</b> <?php echo date("m-d-y", strtotime($ticket_info[0]->arrivalDate));?></p>
                            </address>
                        </div>
                        <div class="pull-left">
                            <address>
                                <h3>&nbsp;</h3>
                                <h4>&nbsp;</h4>
                                <p class="text-muted m-l-10"><b>Guest Email:</b> <?php echo $ticket_info[0]->guestEmail;?></p>
                                <p class="text-muted m-l-10"><b>Room#/Type:</b> <?php echo $ticket_info[0]->guestRoomNumber.' / '.$ticket_info[0]->guestRoomType;?></p>
                                <p class="text-muted m-l-10"><b>Depart Date:</b> <?php echo date("m-d-y", strtotime($ticket_info[0]->departDate));?></p>
                            </address>
                        </div>
                        <!--<div class="pull-right text-right">
                            <address>
                                <h3>To,</h3>
                                <h4 class="font-bold">Gaala & Sons,</h4>
                                <p class="text-muted m-l-30">E 104, Dharti-2,
                                    <br/> Nr' Viswakarma Temple,
                                    <br/> Talaja Road,
                                    <br/> Bhavnagar - 364002</p>
                                <p class="m-t-30"><b>Invoice Date :</b> <i class="fa fa-calendar"></i> 23rd Jan 2016</p>
                                <p><b>Due Date :</b> <i class="fa fa-calendar"></i> 25th Jan 2016</p>
                            </address>
                        </div>-->
                    </div>
                <?php }elseif($ticket_info[0]->houseGuest == 'no'){?>
                    <div class="col-md-12">
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger"><?php $rolename = admin_helper::get_role_name($ticket_info[0]->assign_to_dept); echo $rolename[0]->name; if($ticket_info[0]->serviceRec == 'yes'){echo ' / SERVICE RECOVERY';}?></b></h3>
                                <h4 class="font-bold"><?php if($ticket_info[0]->houseGuest == 'yes'){echo 'In-House';}elseif($ticket_info[0]->houseGuest == 'no'){echo 'Future';}else{echo 'Standard';}?> Guest</h4>
                                <p class="text-muted m-l-10"><b>Guest Name:</b> <?php echo $ticket_info[0]->guestName;?></p>
                                <p class="text-muted m-l-10"><b>Guest Phone:</b> <?php echo $ticket_info[0]->guestNumber;?></p>
                                <?php if($ticket_info[0]->furtherReservation == 'yes'){?>
                                	<p class="text-muted m-l-10"><b>Arrival Date:</b> <?php echo date("m-d-y", strtotime($ticket_info[0]->arrivalDate));?></p>
                                <?php }?>
                            </address>
                        </div>
                        <div class="pull-left">
                            <address>
                                <h3>&nbsp;</h3>
                                <h4>&nbsp;</h4>
                                <p class="text-muted m-l-10"><b>Guest Email:</b> <?php echo $ticket_info[0]->guestEmail;?></p>
                                <?php if($ticket_info[0]->furtherReservation == 'yes'){?>
                                    <p class="text-muted m-l-10"><b>Room Type:</b> <?php echo $ticket_info[0]->guestRoomType;?></p>
                                    <p class="text-muted m-l-10"><b>Depart Date:</b> <?php echo date("m-d-y", strtotime($ticket_info[0]->departDate));?></p>
                                <?php }else{?>
                                	<p class="text-muted m-l-10">No Future Reservation</p>
                                <?php }?>
                            </address>
                        </div>
                    </div>
                <?php }else{?>
                    <div class="col-md-12">
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger"><?php $rolename = admin_helper::get_role_name($ticket_info[0]->assign_to_dept); echo $rolename[0]->name; if($ticket_info[0]->serviceRec == 'yes'){echo ' / SERVICE RECOVERY';}?></b></h3>
                                <h4 class="font-bold"><?php if($ticket_info[0]->houseGuest == 'yes'){echo 'In-House';}elseif($ticket_info[0]->houseGuest == 'no'){echo 'Future';}else{echo 'Standard';}?> Guest</h4>
                            </address>
                        </div>
                    </div>
                <?php }?>
                <?php if($ticket_info[0]->assign_to_dept == 3){?>
                    <div class="col-md-12">
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger">FRONT DESK</b></h3>
                                <p class="text-muted m-l-10"><b>Notes:</b> <?php echo $ticket_info[0]->frontDeskNotes;?></p>
                            </address>
                        </div>
                    </div>
                <?php }?>
                <?php if($ticket_info[0]->assign_to_dept == 4){?>
                    <div class="col-md-12">
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger">HOUSEKEEPING</b></h3>
                                <p class="text-muted m-l-10"><b>Sercive:</b> <?php echo $ticket_info[0]->houseKeepingSer;?></p>
                            </address>
                        </div>
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger">&nbsp;</b></h3>
                                <p class="text-muted m-l-10"><b>Notes:</b> <?php echo $ticket_info[0]->houseKeepingNotes;?></p>
                            </address>
                        </div>
                    </div>
                <?php }?>
                <?php if($ticket_info[0]->assign_to_dept == 5){?>
                    <div class="col-md-12">
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger">FOOD & BEVERAGE</b></h3>
                                <p class="text-muted m-l-10"><b>Sercive:</b> <?php echo ucwords($ticket_info[0]->foodsService);?></p>
                                <p class="text-muted m-l-10"><b>Notes:</b> <?php echo $ticket_info[0]->foodGuestNotes;?></p>
                            </address>
                        </div>
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger">&nbsp;</b></h3>
                                <p class="text-muted m-l-10"><b>Name of group:</b> <?php echo $ticket_info[0]->nameOfGroup;?></p>
                            </address>
                        </div>
                    </div>
                <?php }?>
                <?php if($ticket_info[0]->assign_to_dept == 6){?>
                    <div class="col-md-12">
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger">SALES</b></h3>
                                <p class="text-muted m-l-10"><b>Sercive:</b> <?php echo ucwords($ticket_info[0]->foodsService);?></p>
                                <p class="text-muted m-l-10"><b>Notes:</b> <?php echo $ticket_info[0]->foodGuestNotes;?></p>
                            </address>
                        </div>
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger">&nbsp;</b></h3>
                                <p class="text-muted m-l-10"><b>Name of group:</b> <?php echo $ticket_info[0]->nameOfGroup;?></p>
                            </address>
                        </div>
                    </div>
                <?php }?>
                <?php if($ticket_info[0]->assign_to_dept == 7){?>
                    <div class="col-md-12">
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger">MAINTENANCE</b></h3>
                                <p class="text-muted m-l-10"><b>Sercive:</b> <?php echo ucwords($ticket_info[0]->maintServ);?></p>
                                <p class="text-muted m-l-10"><b>Notes:</b> <?php echo $ticket_info[0]->mainnotes;?></p>
                            </address>
                        </div>
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger">&nbsp;</b></h3>
                                <p class="text-muted m-l-10"><b>Needs:</b> <?php echo $ticket_info[0]->maintExplain;?></p>
                            </address>
                        </div>
                    </div>
                <?php }?>
                <?php if($ticket_info[0]->assign_to_dept == 2){?>
                    <div class="col-md-12">
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger">MANAGER ON DUTY</b></h3>
                                <p class="text-muted m-l-10"><b>Sercive:</b> <?php echo ucwords($ticket_info[0]->mangrDutyConcern);?></p>
                                <p class="text-muted m-l-10"><b>Notes:</b> <?php echo $ticket_info[0]->mingrNotes;?></p>
                            </address>
                        </div>
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger">&nbsp;</b></h3>
                                <p class="text-muted m-l-10"><b>Needs:</b> <?php echo $ticket_info[0]->mangrExpalin;?></p>
                            </address>
                        </div>
                    </div>
                <?php }?>
                <?php if($ticket_info[0]->filename !=''){?>
                	<div class="col-md-12">
                        <div class="pull-left">
                            <address>
                                <h3><b class="text-danger">ATTACHMENT:</b></h3>
                                <p class="text-muted m-l-10"><img src="<?php echo base_url();?>assets/images/ticket_images/<?php echo $ticket_info[0]->filename;?>" width="300" height="300"/> </p>
                            </address>
                        </div>
                    </div>
                <?php }?>
                </div><?php */?>
            </div>
        </div>
    </div>
</div>
<style>
	 blink {
	   color:red;
	   -webkit-animation: blink 1s step-end infinite;
	   animation: blink 1s step-end infinite
	 }

	  @-webkit-keyframes blink {
	  67% { opacity: 0 }
	 }

	 @keyframes blink {
	 67% { opacity: 0 }
	}
.indicator {
    width: 10px;
    height: 10px;
    display: inline-block;
    border-radius: 9999px;
    margin-right: 5px;
}
.label-success {
    background-color: #8ad919;
}
.label-danger {
    background-color: #F00;
}
</style>